import { createTheme } from "@shopify/restyle";

const palette = {
  background: "hsl(220 20% 7%)",
  foreground: "hsl(210 20% 95%)",
  card: "hsl(220 18% 11%)",
  primary: "hsl(160 64% 40%)",
  primary10: "hsla(160 64% 40% / 0.1)",
  secondary: "hsl(220 16% 16%)",
  muted: "hsl(220 14% 14%)",
  mutedForeground: "hsl(215 12% 55%)",
  destructive: "hsl(0 72% 55%)",
  border: "hsl(220 14% 18%)",
  success: "hsl(160 64% 40%)",
  warning: "hsl(40 90% 55%)",
  info: "hsl(200 70% 50%)",
  chart4: "hsl(280 60% 55%)",
  chart5: "hsl(350 70% 55%)",
  container: "#2c2f33",
};

const theme = createTheme({
  colors: {
    ...palette,
    containerBackground: palette.background,
    mainBackground: palette.background,
    mainForeground: palette.foreground,
    cardBackground: palette.card,
    textPrimary: palette.foreground,
    textSecondary: palette.mutedForeground,
    textTertiary: palette.mutedForeground,
    textInverse: palette.background,
    textLink: palette.primary,
    border: palette.border,
    borderFocus: palette.primary,
    borderError: palette.destructive,
    buttonPrimary: palette.primary,
    buttonPrimaryText: palette.background,
    buttonSecondary: palette.secondary,
    buttonSecondaryText: palette.foreground,
    buttonDisabled: palette.muted,
    buttonDisabledText: palette.mutedForeground,
    success: palette.success,
    successLight: palette.success,
    successDark: palette.success,
    warning: palette.warning,
    warningLight: palette.warning,
    warningDark: palette.warning,
    error: palette.destructive,
    errorLight: palette.destructive,
    errorDark: palette.destructive,
    info: palette.info,
    infoLight: palette.info,
    infoDark: palette.info,
    overlay: "rgba(0, 0, 0, 0.5)",
    shadow: "rgba(0, 0, 0, 0.2)",
    hover: palette.secondary,
    pressed: palette.muted,
  },
  spacing: {
    xs: 4,
    s: 8,
    m: 16,
    l: 24,
    xl: 32,
    xxl: 40,
    xxxl: 48,
  },
  borderRadii: {
    xs: 4,
    s: 8,
    m: 12,
    l: 16,
    xl: 24,
    full: 9999,
  },
  textVariants: {
    header: {
      fontWeight: "bold",
      fontSize: 34,
      color: "textPrimary",
    },
    subheader: {
      fontWeight: "600",
      fontSize: 24,
      color: "textPrimary",
    },
    body: {
      fontSize: 16,
      lineHeight: 24,
      color: "textPrimary",
    },
    caption: {
      fontSize: 14,
      lineHeight: 20,
      color: "textSecondary",
    },
    small: {
      fontSize: 12,
      lineHeight: 16,
      color: "textTertiary",
    },
    defaults: {
      fontSize: 16,
      color: "textPrimary",
    },
  },
});

export type Theme = typeof theme;
export { palette };
export default theme;
